[build]
publish = "public"
command = "npm run build"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[headers]]
  for = "/js/*"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "/sass/*"
  [headers.values]
    cache-control = "max-age=31536000"
